### ISSUE TITLE
frame interval and frame rate are conflated compared to the v4l2 implementation

### ISSUE THREAD

**Issue by matanox** [antmicro/pyrav4l2#8]
Thank you again for pyrav4l2!

I notice on my system with my cameras, that class `FrameInterval` reports the frame rate, not the frame interval, in its `__str__` implementation. Going into the source, [we have there](https://github.com/antmicro/pyrav4l2/blob/ee5332d9868198ad9c825d8ad853d02ec38b6dd8/pyrav4l2/device.py#L47-L57):

```python
    def __str__(self) -> str:
        if self.numerator != 0:
            return str(self.denominator / self.numerator)
        else:
            return "0.0"
```

However, in the output of an equivalent v4l2-ctl for the same cameras, it is obvious that what the above code yields is the frame rate, (fps) not the frame interval. Which is also confirmed by juxtaposing with the Github copy of v4l2-ctl itself at https://github.com/cz172638/v4l-utils/blob/7b2d48ff594dcc2c9b395463441e5abb4f5e9439/utils/v4l2-ctl/v4l2-ctl-vidcap.cpp#L79-L93.

Is that string representation intentionally flipped?

Otherwise, I'd consider providing one method returning the _frame interval_ and one method returning the _frame rate_, if this code is to be touched to fix the former. Actually as a matter of design perhaps returning the value as a number type makes more sense for library users, unless this needs to be a string when passed as an input argument to other functions of pyrav4l2. 

Having to use the denominator and numerator to access the numeric frame interval seems like an under-abstraction of how things work for the rest of us who just want to know the intervals ― in such a case it's nice to abstract over that v4l2 detail by returning the actual interval on a method or property of the `FrameInterval` class ― leaving less room for confusion in using the numerator and denominator. I guess it depends on how much the intent of the library is to abstract over things as opposed to provide detailed access to anything that v4l2-ctl can do.

**Comment by tgorochowik** [comment]
Fixed in #9
